/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainLayoutRouteImport } from './routes/_main-layout'
import { Route as MainLayoutIndexRouteImport } from './routes/_main-layout.index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as MainLayoutProfileRouteImport } from './routes/_main-layout.profile'
import { Route as MainLayoutPostPictureRouteImport } from './routes/_main-layout.post-picture'

const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_main-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutIndexRoute = MainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutProfileRoute = MainLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutPostPictureRoute = MainLayoutPostPictureRouteImport.update({
  id: '/post-picture',
  path: '/post-picture',
  getParentRoute: () => MainLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainLayoutIndexRoute
  '/post-picture': typeof MainLayoutPostPictureRoute
  '/profile': typeof MainLayoutProfileRoute
  '/auth/login': typeof AuthLoginRoute
}
export interface FileRoutesByTo {
  '/post-picture': typeof MainLayoutPostPictureRoute
  '/profile': typeof MainLayoutProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof MainLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main-layout': typeof MainLayoutRouteWithChildren
  '/_main-layout/post-picture': typeof MainLayoutPostPictureRoute
  '/_main-layout/profile': typeof MainLayoutProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/_main-layout/': typeof MainLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/post-picture' | '/profile' | '/auth/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/post-picture' | '/profile' | '/auth/login' | '/'
  id:
    | '__root__'
    | '/_main-layout'
    | '/_main-layout/post-picture'
    | '/_main-layout/profile'
    | '/auth/login'
    | '/_main-layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main-layout': {
      id: '/_main-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main-layout/': {
      id: '/_main-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main-layout/profile': {
      id: '/_main-layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainLayoutProfileRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/post-picture': {
      id: '/_main-layout/post-picture'
      path: '/post-picture'
      fullPath: '/post-picture'
      preLoaderRoute: typeof MainLayoutPostPictureRouteImport
      parentRoute: typeof MainLayoutRoute
    }
  }
}

interface MainLayoutRouteChildren {
  MainLayoutPostPictureRoute: typeof MainLayoutPostPictureRoute
  MainLayoutProfileRoute: typeof MainLayoutProfileRoute
  MainLayoutIndexRoute: typeof MainLayoutIndexRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutPostPictureRoute: MainLayoutPostPictureRoute,
  MainLayoutProfileRoute: MainLayoutProfileRoute,
  MainLayoutIndexRoute: MainLayoutIndexRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainLayoutRoute: MainLayoutRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
